version: "3.1"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - apis
    ports:
      - 3000:80
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
  cache:
    image: "redis:alpine"
  apis:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      PGUSER: postgres
      PGHOST: db
      PGDATABASE: postgres
      PGPASSWORD: postgres_password
      PGPORT: 5432
    depends_on:
      - db
      - cache
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
